### ISSUE TITLE
To add new starter template

### ISSUE THREAD

**Issue by motss** [web-padawan/awesome-lit-html#10]
I've spent some time creating this generator for people who wants to develop their custom element in `TypeScript` with latest `lit-element`. I've also included the basic stuff they need such as `TSLint` and testing with `wct`.

I see a issue thread saying that not everything can be added and some requires review, so I created this issue for that.

Here's the link to the repo: https://github.com/motss/generator-lit-element-next

**Comment by web-padawan** [comment]
Thanks for the suggestion. Let's see how the project evolves, and I will be glad to add it to the list.
Wondering why do you restrict users to the node > 10.13 and npm > 6.4 ? Just curious.

**Comment by motss** [comment]
@web-padawan There is no restriction just that while I'm creating the project. Those are the version I use plus those are the latest LTS version I believe and I do understand that not everyone has switched over the new LTS but still comfortable with Node 8.x.

**Comment by web-padawan** [comment]
@motss hey, are you still working on that project? In case you do, please update to the stable releases of lit-html and lit-element and then I will merge this PR.

**Comment by motss** [comment]
Sure. I'm on vacation. Will do that once I got back.

**Comment by motss** [comment]
@web-padawan Done with the upgrade with new [v1.2.0](https://www.npmjs.com/package/generator-lit-element-next) release.
