### ISSUE TITLE
lit-html channel in Polymer slack no longer exists

### ISSUE THREAD

**Issue by stramel** [web-padawan/awesome-lit-html#27]
Update documentation to point to #general instead of #lit-html

Also, side note: Doesn't look like the team is using `@lit-html` twitter for anything anymore.

**Comment by web-padawan** [comment]
Nice catch. Should have done that earlier. Will update the Slack link.

**Comment by web-padawan** [comment]
Fixed by 8cf16f8
Regarding the twitter, will consider pointing to `@polymer` instead
