### ISSUE TITLE
functional-web-component has been deprecated. It is now called fuco.

### ISSUE THREAD

**Issue by motss** [web-padawan/awesome-lit-html#41]
## Description

[functional-web-component] has been deprecated in favor of [fuco].

See the [deprecation notice](https://www.npmjs.com/package/functional-web-component) instead.

[functional-web-component]: https://www.npmjs.com/package/functional-web-component
[fuco]: https://www.npmjs.com/package/fuco

**Comment by web-padawan** [comment]
Thanks, fixed by ff3e723
