### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by boguz** [web-padawan/awesome-lit-html#43]
Hi.

I know your list for a while now.
I have been working on a lit-component element, which is now available also on npm (still testing), and i thought i would write you to ask what you think about it.
This is when i noticed i couldn't find a way to suggest any new components / libraries / ideas for your list.
So i am writing you here, i hope it is ok. If not, please just close and delete the issue.

Anyway, if you have the time, i would love to know what you think about my [burgton-button](https://github.com/boguz/burgton-button), a simple, customizable and accessible lit-element powered burger button.

thank you!

**Comment by web-padawan** [comment]
Thanks for the PR! There is a [contribution guideline](https://github.com/web-padawan/awesome-lit-html/blob/master/CONTRIBUTING.md) describing require the process.

I checked your button component and it looks great! So, feel free to submit a PR.
The appropriate section would be [Individual Components](https://github.com/web-padawan/awesome-lit-html#individual-components), pease follow the alphabetical order.

**Comment by web-padawan** [comment]
Closed by #44
