### ISSUE TITLE
Babel plugin for tranforming JSX to lit-html

### ISSUE THREAD

**Issue by phaux** [web-padawan/awesome-lit-html#8]
I made this plugin for babel. It transforms JSX to lit-html syntax. You might consider adding it to your list. :wink: 

https://github.com/phaux/babel-jsx-lit-html

**Comment by web-padawan** [comment]
Thanks for the issue. Please follow the discussion in Slack channel:
https://polymer.slack.com/archives/C6TEC35M4/p1538485280000100

After discussion with @43081j this plugin looks a bit confusing, and seems questionable to me.
I would like to see at least some real examples with a proper Babel config to make sure it does the job.

**Comment by 43081j** [comment]
I would still introduce this into your list as there's no other solid implementation of it either.

However the syntax limitations are something that I wasn't so sure about as it could lead people into thinking the legacy syntax is what lit uses (it doesn't). Though there's no way to support the new syntax in babel or typescript so this good effort/workaround.

**Comment by web-padawan** [comment]
Closing as there hasn't been any activity since the creation of that project.
